### ISSUE TITLE
Getting issues in case of Redirect URL - control never reached the response handler

### ISSUE THREAD

**Issue by MakSheron** [timboudreau/netty-http-client#3] opened 2015-03-12 08:50 UTC
Hi,
I wrote a unit test case and tried testing the http client with the redirected url and setting the timeout (setTimeout(Timeout in milliseconds - Duration)). But the control never reached the response handler. I set the timeout to max possible value as well to check if it is a timeout issue, but it was not the case.
After debugging, I found that there is an atomic boolean variable named cancelled which is getting set at a certain point of time which triggers the job to get failed. 

It is working perfectly fine in case of url which is not redirecting in nature. It also works fine with the redirected url if I don't set the timeout.

Is this a known issue or am I missing something here? Please help me out in getting this working with a redirected url and a request timeout.

Thanks
Sheron

**Comment by timboudreau** [comment] 2015-03-12 15:59
Yeah, I think that is a legit bug - cancelled should not be set or should be reset and used for the redirect.

**Comment by MakSheron** [comment] 2015-03-15 18:37
Thanks for the quick response. I have few queries:
1. What is the cancelled  used for?
2. Any pointers to prevent cancelled from getting set/reset during redirect url.
3. Does the timeout set by using setTimeout function include both the read and connect time?

**Comment by timboudreau** [comment] 2015-03-15 22:16
Connect time is taken care of by the appropriate Netty ChannelOption (you can set it on the HttpClientBuilder or as a constructor argument).

Cancelled is used for cancelling a request that has been made before it completes - useful, for example, in [tiny-maven-proxy](https://github.com/timboudreau/tiny-maven-proxy) which makes concurrent requests to several URLs and one one responds with 200, cancels the other.

The problem is that redirecting is implemented as issuing a new HTTP request, which gets a new timer and a new cancelled `AtomicBoolean` - it means splitting the private `HttpClient.submit()` to have a variant that takes an existing timer and `AtomicBoolean` rather than create a new one.

**Comment by timboudreau** [comment] 2015-06-15 06:24
Fixed in version 1.6.2.

**Closed by timboudreau** 2015-06-15 06:24 UTC
Labels: bug
